//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEmbarques.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assemblies
    {
        public int AssemblyID { get; set; }
        public string AssemblyPartNumber { get; set; }
        public Nullable<int> AreaID { get; set; }
        public string BinLocation { get; set; }
        public string Image { get; set; }
        public Nullable<byte> Quantity { get; set; }
    
        public virtual Areas Areas { get; set; }
    }
}
