//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEmbarques.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BAESystemsGuaymasEntities : DbContext
    {
        public BAESystemsGuaymasEntities()
            : base("name=BAESystemsGuaymasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Assembly> Assemblies { get; set; }
        public virtual DbSet<CatalogShipmentType> CatalogShipmentType { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Component> Components { get; set; }
        public virtual DbSet<Shipping_Catalog_Products> Shipping_Catalog_Products { get; set; }
        public virtual DbSet<Shipping_Records> Shipping_Records { get; set; }
        public virtual DbSet<WireKit> WireKits { get; set; }
        public virtual DbSet<VIEWDATA> VIEWDATA { get; set; }
    }
}
