//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEmbarques.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MaterialShippingControlEntities : DbContext
    {
        public MaterialShippingControlEntities()
            : base("name=MaterialShippingControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<VIEWDATA> VIEWDATA { get; set; }
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<Assemblies> Assemblies { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<WireKit> WireKit { get; set; }
        public virtual DbSet<Shipping_Catalog_Products> Shipping_Catalog_Products { get; set; }
        public virtual DbSet<Shipping_Catalog_ShipmentTypes> Shipping_Catalog_ShipmentTypes { get; set; }
        public virtual DbSet<Shipping_Records> Shipping_Records { get; set; }
    }
}
