//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEmbarques.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shipping_Catalog_Products
    {
        public Shipping_Catalog_Products()
        {
            this.Shipping_Records = new HashSet<Shipping_Records>();
        }
    
        public int ProductID { get; set; }

        [Required(ErrorMessage = "Nombre del Area requerida.")]
        public int AreaID { get; set; }

        [Required(ErrorMessage = "Nombre del producto requerido.")]
        public string ProductName { get; set; }

        [Required(ErrorMessage = " Area Interna requerida.")]
        public string ProductInternalArea { get; set; }

        [Required(ErrorMessage = "Tipo del producto requerido.")]
        public string ProductType { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual ICollection<Shipping_Records> Shipping_Records { get; set; }
    }
}
