//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEmbarques.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shipping_Records
    {
        public int RecordID { get; set; }
        [Required(ErrorMessage = "Nombre del cliente requerido.")]
        public int ClientID { get; set; }

        [Required(ErrorMessage = "No. de parte requerida.")]
        public int ProductID { get; set; }

        [Required(ErrorMessage = "Cantidad requerida.")]
        public int RecordQuantity { get; set; }

        public System.DateTime RecordDate { get; set; }

        [Required(ErrorMessage = "Tracking de fedex requerido.")]
        public string RecordFedexTracking { get; set; }

        [Required(ErrorMessage = "No. de caja con Doc. requerido.")]
        public string RecordControlBoxNo { get; set; }

        [Required(ErrorMessage = "No. de caja con piezas requerido.")]
        public int RecordPieceBoxNo { get; set; }

        [Required(ErrorMessage = "Tipo de Embarque requerido.")]
        public int ShipmentTypeID { get; set; }

        [Required(ErrorMessage = "Tipo de servicio requerido.")]
        public string RecordServiceType { get; set; }


        public string RecordComment { get; set; }
        public string RecordWorkOrder { get; set; }
        public string RecordSerialNo { get; set; }
        public string RecordTrackingId { get; set; }
        public string RecordRework { get; set; }
        public string RecordComment1 { get; set; }
        public string RecordComment2 { get; set; }
        public string RecordFAI { get; set; }
        public string RecordSeguritySeal1 { get; set; }
        public string RecordSeguritySeal2 { get; set; }
        public string RecordSeguritySeal3 { get; set; }
        public string RecordSeguritySeal4 { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual CatalogShipmentType CatalogShipmentType { get; set; }
        public virtual Shipping_Catalog_Products Shipping_Catalog_Products { get; set; }
    }
}
