//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoEmbarques.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Shipping_Records
    {
        [ScaffoldColumn(false)]
        public int RecordID { get; set; }

        [Required(ErrorMessage = "Nombre del cliente requerido.")]
        public int ClientID { get; set; }

        [Required(ErrorMessage = "No. de parte requerida.")]
        public int ProductID { get; set; }

        [Required(ErrorMessage = "Cantidad requerida.")]
        public int RecordQuantity { get; set; }

        public System.DateTime RecordDate { get; set; }

        [Required(ErrorMessage = "Tracking de fedex requerido.")]
        public decimal RecordFedexTracking { get; set; }

        [Required(ErrorMessage = "No. Caja Con Doc. requerido.")]
        public decimal RecordControlBoxNo { get; set; }

        [Required(ErrorMessage = "No. Caja de Piezas requerido.")]
        public decimal RecordPieceBoxNo { get; set; }

        [Required(ErrorMessage = "Tipo de Embarque requerido.")]
        public int ShipmentTypeID { get; set; }

        [Required(ErrorMessage = "Tipo de Servicio requerido.")]
        public string RecordServiceType { get; set; }

        public string RecordComment { get; set; }

        public Nullable<decimal> RecordWorkOrder { get; set; }

        public Nullable<decimal> RecordSerialNo { get; set; }

        public Nullable<decimal> RecordTrackingId { get; set; }

        public string RecordRework { get; set; }

        public string RecordComment1 { get; set; }

        public string RecordComment2 { get; set; }

        public string RecordFAI { get; set; }

        [Required(ErrorMessage = "Sello de Seguridad requerido.")]
        public string RecordSeguritySeal1 { get; set; }

        [Required(ErrorMessage = "Sello de Seguridad requerido.")]
        public string RecordSeguritySeal2 { get; set; }

        [Required(ErrorMessage = "Sello de Seguridad requerido.")]
        public string RecordSeguritySeal3 { get; set; }

        [Required(ErrorMessage = "Sello de Seguridad requerido.")]
        public string RecordSeguritySeal4 { get; set; }

        public string RecordTransfer { get; set; }

        public virtual Clients Clients { get; set; }
        public virtual CatalogShipmentType CatalogShipmentType { get; set; }
        public virtual Shipping_Catalog_Products Shipping_Catalog_Products { get; set; }
    }
}
